INSERT IGNORE INTO Instructor (email, last_name, first_name, desired_load)
VALUES
	('gosnat@bethel.edu', 'Gossett', 'Nathan', 23.5),
    ('j-yang@bethel.edu', 'Yang', 'Jed', 23.5),
    ('t-auch@bethel.edu', 'Auch', 'Tanner', 23.5),
    ('d-thomas@bethel.edu', 'Thomas', 'Deborah', 23.5),
    ('yacste@bethel.edu', 'Yackel', 'Steven', 16.7),
    ('dunn@bethel.edu', 'Dunn', 'Lawrence', 12.4),
    ('wilkin@bethel.edu', 'Kinney', 'William', 23.5),
    ('huben@bethel.edu', 'Shull', 'Ben', 18.4),
    ('alebar@bethel.edu', 'Aybar', 'Alex', 21.7),
    ('rutliv@bethel.edu', 'Livingston', 'Ruth', 23.8);

INSERT IGNORE INTO Course (course_id, department, course_title, num_credits)
VALUES
	(1101, 'Computer Science', 'Intro to Programming', 4),
    (2102, 'Math', 'Precalculus', 3),
    (1104, 'Computer Science', 'Object Oriented Programming', 4),
    (1212, 'Computer Science', 'Data Structures', 3),
    (1216, 'Computer Science', 'Algorithms', 4),
    (1235, 'Computer Science', 'Computer Systems', 3),
    (1313, 'Computer Science', 'Database Systems', 4),
    (1351, 'Computer Science', 'High Performance Computing', 4),
    (1389, 'Computer Science', 'Artificial Intelligence', 3),
    (2104, 'Math', 'Calculus', 3),
    (2110, 'Math', 'Calculus 2', 3),
    (2200, 'Math', 'Multivariable Calculus', 3),
    (2214, 'Math', 'Discrete Mathematics', 3),
    (2221, 'Math', 'Linear Algebra', 3),
    (2310, 'Math', 'Differential Equations', 3),
    (2311, 'Math', 'Differential Equations and Linear Algebra', 4),
    (3100, 'English', 'How Stories Change the World', 3),
    (3101, 'English', 'British Literature I', 3),
    (3110, 'English', 'Introduction to Creative Writing', 3),
    (3111, 'English', 'Introduction to Professional and Technical Writing', 3),
    (3120, 'English', 'Reporting I', 3),
    (3121, 'English', 'Digital Storytelling', 3),
    (3203, 'English', 'World Literature', 3),
    (5400, 'Art', 'Underwater Basket Weaving', 4),
    (4200, 'History', 'American Civilization', 3),
    (4212, 'History', 'History of Islam', 3),
    (4216, 'History', 'American Constitutional History', 3),
    (4290, 'History', 'Introduction to History', 3),
    (4320, 'History', 'History and the Human Environment', 3),
    (4324, 'History', 'Human Rights in International History', 3),
    (4333, 'History', 'History of Crime and Punishment', 3)